if(health = 1){
	sprite_index = spr_health1;
} else if(health = 2){
	sprite_index = spr_health2;
} else if(health = 3){
	sprite_index = spr_health3;
} else if(health = 4){
	sprite_index = spr_health4;
} else if(health = 5){
	sprite_index = spr_health5;
} else if(health = 6){
	sprite_index = spr_health6;
} else if(health = 7){
	sprite_index = spr_health7;
} else if(health = 8){
	sprite_index = spr_health8;
} else if(health = 9){
	sprite_index = spr_health9;
} else {sprite_index = spr_health_more;}